openapi: 3.0.0
info:
  title: Portfolio Data Production
  description: Restful API that collects selected projects' data for my portfolio website, built with TypeScript, ExpressJS, Non Relational Database MongoDB and Mongoose Modelling library
  contact:
    name: Gladwin Tshepo Ramantso
    url: https://gladwinramantso.netlify.app/#home
    email: tshepo.ramantso@outlook.com
  version: "1.0"
servers:
  - url: https://personal-portfolio-data.onrender.com/api/v1
    variables: {}
paths:
  /projects:
    get:
      tags:
        - Projects
      summary: Get all projects
      operationId: GetAllProjects
      parameters:
        - name: sort
          in: query
          required: true
          schema:
            type: string
            example: title
      responses:
        "200":
          description: ""

  /projects/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The project ID
    get:
      tags:
        - Projects
      summary: Get single project
      operationId: GetSingleProject
      responses:
        "200":
          description: ""
